apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
        - image: ghcr.io/2022-4400-exp/4443-go-helloworld-2:4bdbe9d2157fe21208cfeef78817c7fb9768dbf2
          name: go-helloworld-2
